["bili2233.cn"]
action = "request"
content_regex = 'href="(.*)"'
["b23.tv"]
action = "request"
content_regex = 'href="(.*)"'
["www.bilibili.com"]
action = "direct_script"
params = ["t", "p"]
script = "bilibili"
["bilibili.com"]
action = "direct_script"
params = ["t", "p"]
script = "bilibili"

["m.tb.cn"]
action = "request"  # 处理 URL 请求的内容
content_regex = "var url = '([^']*)'"
r_params = ["id"]

["chaoshi.detail.tmall.com"]
params = ["id"]
["detail.tmall.com"]
params = ["id"]
["item.taobao.com"]
params = ["id"]
["h5.m.goofish.com"]
params = ["id"]
["h5.m.taobao.com"]
params = ["id"]

["a.co"]
action = "redirect" # 获取301跳转目标

["xhslink.com"]
action = "redirect"

["www.coolapk.com"]
params = ["shareKey"]

["qr.ae"]
action = "redirect"

["t.co"]
action = "redirect"

["y.music.163.com"]
params = ["id"]

["music.163.com"]
action = "regex"
url_regex = '/([^/]*)\?(id=\d+)'
url_expand = 'https://music.163.com/#/\1?\2'

["163cn.tv"]
action = "redirect"

["u.jd.com"]
action = "request_redirect"
content_regex = "var hrl='([^']*)'"

["mdisk.pro"]
action = "request"
content_regex = "document.location = \\('([^#]*)#"

["tnlink.in"]
action = "redirected_request"
content_regex = 'window.location.href = "([^"]*)"'
["tnshort.in"]
action = "redirected_request"
content_regex = 'window.location.href = "([^"]*)"'

["www.google.com"]
params = ["url", "q"]

["m.acfun.cn"]
params = ["ac"]
