["b23.tv"]
action = "request"
content_regex = 'href="(.*)"'

["m.tb.cn"]
action = "request"  # 处理 URL 请求的内容
content_regex = "var url = '(.*)'"
r_params = ["id"]

["chaoshi.detail.tmall.com"]
params = ["id"]
["detail.tmall.com"]
params = ["id"]
["item.taobao.com"]
params = ["id"]
["h5.m.goofish.com"]
params = ["id"]

["a.co"]
action = "redirect" # 获取301跳转目标

["xhslink.com"]
action = "request"
content_regex = 'href="(.*)"'

["www.coolapk.com"]
params = ["shareKey"]

["qr.ae"]
action = "redirect"

["t.co"]
action = "redirect"

["y.music.163.com"]
params = ["id"]
["music.163.com"]
params = ["id"]
